#!/usr/bin/python

import os
from fnmatch import fnmatch


def get_name(filename):
    return os.path.splitext(filename)[0]

def list_dir(dir_path, filter_func):
    return sorted(filter(filter_func, os.listdir(dir_path)), key=get_name)

def main():
    disabled_tests = [x.split("#")[0].strip() for x in file("disabled-testcases").readlines()]

    def is_testcase_file(filename):
        return (
            fnmatch(filename, "*.html") and 
            not fnmatch(filename, "manual-test*") and 
            filename not in disabled_tests)

    test_dir = os.path.dirname(os.path.realpath(__file__))
    testcase_dir = os.path.join(test_dir, 'testcases')
    with open(os.path.join(test_dir, 'testcases.jsonp'), 'w') as testcases_file:
        testcases_file.write(
            '// This file is automatically generated by test/update-testcases.py.\n')
        testcases_file.write(
            '// Disable tests by adding them to test/disabled-testcases.jsonp.\n')
        testcases_file.write('testCases([\n    "')
        testcases_file.write('",\n    "'.join(list_dir(testcase_dir, is_testcase_file)))
        testcases_file.write('"]);\n')


if __name__ == '__main__':
    main()
