language: python

env:
  - BROWSER=Chrome-stable
  - BROWSER=Chrome-beta
  - BROWSER=Chrome-unstable
  - BROWSER=Firefox-stable
  - BROWSER=Firefox-beta
  - BROWSER=Firefox-aurora

#matrix:
#  allow_failures:
#    - env: BROWSER=Firefox

notifications:
  irc: "irc.freenode.org#webanimations"
  skip_join: true
  template:
    - "%{repository}#%{build_number} %{branch}: %{message}"

install:
  - ./.travis-setup.sh

script:
  - python ./test/update-testcases.py --dry-run || (echo "Please run update-testcases!"; false)
  - python run-tests.py -a -u -x -b $(echo $BROWSER | sed -e's/-.*//')

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true
